f123();
console.log('A');
console.log('S');
console.log('Z');
f123();
console.log('D');
console.log('E');
console.log('Q');
f123();
console.log('X');
console.log('F');
console.log('R');
f123();
console.log('Y');
console.log('U');
console.log('I');
f123();
function f123(){
    console.log(1);
    console.log(2);
    console.log(3);
}